import * as ListRouter from "./import"

export const routes_user = [

]

export const routes_gid = [
    
]

export const routes = [
    {
        url:'/auth',
        component:ListRouter.Auth
    },
    {
        url:"/auth/verify",
        component:ListRouter.Verify
    },
    {
        url:'/auth/update-password',
        component:ListRouter.UpdatePassword
    },
    {
        url:"/auth/reset",
        component:ListRouter.ResetPassword
    },
    {
        url:'/about',
        component:ListRouter.About
    },
    {
        url:'/gids',
        component:ListRouter.ChooseGids,
    },
    {
        url:'/forgits',
        component:ListRouter.Forgits
    },
    {
        url:'/connect',
        component:ListRouter.Connect
    },
    {
        url:'/main',
        component:ListRouter.MainPage
    },
    {
        url:'/application-form',
        component:ListRouter.FillOutApplication,
    },
    {
        url:'/request',
        component:ListRouter.Request
    },
    {
        url:'/fullrequest',
        component:ListRouter.Fullrequest
    },
    {
        url:'/cities',
        component:ListRouter.Cities
    },
    {
        url:'/fulldata',
        component:ListRouter.FullData,
    },
    {
        url:'/gid-personal',
        component:ListRouter.GidPersonal
    },
    {
        url:'/gid-personal-wider',
        component:ListRouter.GidPersonalWider
    },
    {
        url:'/article',
        component:ListRouter.Article
    },
    {
        url:'/answer-me',
        component:ListRouter.AnsverMyapp
    },
    {
        url:'/blog',
        component:ListRouter.Blog
    },
    {
        url:'/advertising',
        component:ListRouter.Advertising
    },
    {
        url:'/pay',
        component:ListRouter.Pay
    },
    {
        url:'/reklama',
        component:ListRouter.Reklama
    },
    {
        url:'*',
        component:ListRouter.notFound
    },
]