export const GIDS = {
    ABOUT_EDIT_BIO:"ABOUT_EDIT_BIO",
    ABOUT_EDIT_BIO_ERROR:"ABOUT_EDIT_BIO_ERROR",
    ABOUT_UPDATE_BIO: "ABOUT_UPDATE_BIO",
    ABOUT_UPDATE_BIO_ERROR: "ABOUT_UPDATE_BIO_ERROR"
}